server:
  port: 8083

spring:
  application:
    name: equipment-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/equipment_db
    username: ${POSTGRES_USER:vortex_admin_samir}
    password: ${POSTGRES_PASSWORD:vortex_admin_samir_samirsaudagar}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
